# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/.Xil/Vivado-6752-DESKTOP-7NB8043/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/Enchanced_Single-Cycle_MIPS_Processor {
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/new/HiLo_reg.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/adder.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/alu.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/control_unit/auxdec.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/basys3_single_cycle_mips_validation/button_debouncer.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/basys3_single_cycle_mips_validation/clk_gen.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/control_unit/controlunit.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/datapath.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/memory/dmem.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/dreg.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/basys3_single_cycle_mips_validation/hex_to_7seg.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/memory/imem.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/basys3_single_cycle_mips_validation/led_mux.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/control_unit/maindec.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/mips/mips.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/mips/mips_top.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/mux2.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/new/mux4.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/new/pipelined_multiplier.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/regfile.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/single_cycle_mips_source_initial/datapath/signext.v
      C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor.srcs/sources_1/imports/imports/basys3_single_cycle_mips_validation/mips_fpga.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mips_fpga
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Vivado/CMPE-140/A7_Enhanced_Single-Cycle_MIPS_Processor/Enchanced_Single-Cycle_MIPS_Processor/.Xil/Vivado-6752-DESKTOP-7NB8043/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
